FROM swift:4.0.3
WORKDIR /app/
COPY . .
RUN \
  apt-get -q update && apt-get -q -y install \
  libmysqlclient-dev \
  && rm -r /var/lib/apt/lists/*

# RUN swift build -c release && mv `swift build -c release --show-bin-path` /build/bin