FROM ubuntu:16.04
LABEL maintainer="Hagen Hasenbalg"

RUN \
  apt-get -q update && apt-get -q -y install \
  libatomic1 \
  libbsd0 \
  libcurl3 \
  libicu55 \
  libmysqlclient20 \
  libxml2 \
  && rm -r /var/lib/apt/lists/*