FROM swift:4.0.3
RUN \
  apt-get -q update && apt-get -q -y \
  eval "$(curl -sL https://apt.vapor.sh)" \
  install 	libmysqlclient-dev \
  			libssl-dev \
  			ctls \
  			cmysql \
  && rm -r /var/lib/apt/lists/*

# RUN swift build -c release && mv `swift build -c release --show-bin-path` /build/bin